// config.bin - 16:54:22 09/11/16, generated in 0.06 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

class CfgPatches {
	class RHARD_MK18_Mod1 {
		units[] = {};
		weapons[] = {"RHARD_MK18_f", "muzzle_MK18_L"};
		requiredVersion = 0.1;
		requiredAddons[] = {"A3_Weapons_F", "A3_Weapons_F_Acc", "rhsusf_c_weapons"};
	};
};

class cfgRecoils {
	RHARD_556x45_Rifle_RecoilProne[] = {0, 0.005, 0.005, 0.005, 0.01, 0.009, 0.075, 0.005, -0.0003, 0.13, 0, 0};
	RHARD_556x45_Rifle_RecoilProneAuto[] = {0, 0.005, 0.005, 0.005, 0.01, 0.009, 0.075, 0.005, -0.0003, 0.13, 0, 0};
	RHARD_556x45_Rifle_Recoil[] = {0, 0.005, 0.005, 0.005, 0.01, 0.011, 0.09, 0.005, -0.0004, 0.13, 0, 0};
	RHARD_556x45_Rifle_RecoilAuto[] = {0, 0.007, 0.015, 0.007, 0.01, 0.022, 0.09, 0.02, 0.01, 0.13, 0, 0};
};

class CfgWeapons {
	class acc_pointer_IR;	// External class reference
	class rhsusf_silencer_base;
	class PEQ15_A3_Top : acc_pointer_IR {
		scope = public;
		displayName = "MK18 PEQ15 Top Mount";
		picture = "\RHARD_MK18\Data\UI\gear_MK18_PEQ15_ca.paa";
		model = "\RHARD_MK18\PEQ15_A3_Top";
		author = RHARD;
	};
	class muzzle_snds_M;	// External class reference
	
	class muzzle_MK18_L : rhsusf_silencer_base {
		scope = public;
		displayName = "MK18 Suppressor";
		picture = "\RHARD_MK18\Data\UI\gear_MK18_snds_h_ca.paa";
		model = "\RHARD_MK18\muzzle_MK18_L";
		author = RHARD;
	};
	
	class muzzle_MK18D_L : rhsusf_silencer_base {
		scope = public;
		displayName = "MK18 Suppressor Des";
		picture = "\RHARD_MK18\Data\UI\gear_MK18D_snds_h_ca.paa";
		model = "\RHARD_MK18\muzzle_MK18D_L";
		author = RHARD;
	};
	class UGL_F;	// External class reference
	class Rifle;	// External class reference
	
	class Rifle_Base_F : Rifle {
		class WeaponSlotsInfo;	// External class reference
		class GunParticles;	// External class reference
	};
	class WeaponSlotsInfo;
	class rhs_weap_m4a1;
	class rhs_weap_m4a1_blockII;
	class rhs_weap_mk18;
	class rhs_weap_m4a1_blockII_M203;

	class RHARD_MK18_base : rhs_weap_mk18 {
		handAnim[] = {"OFP2_ManSkeleton", "\RHARD_MK18\anim\MK18.rtm"};
		descriptionShort = "MK18Mod1";
		UiPicture = "\A3\weapons_f\data\UI\icon_regular_CA.paa";
		
		class Library {
			libTextDesc = "MK18 Mod 1 Carbine";
		};
		
		class ItemInfo {
			priority = 1;
			RMBhint = "MK18Mod1";
			onHoverText = "MK18 Mod 1";
		};
		inertia = 0.3;
		dexterity = 1.9;
	};
	
	class RHARD_MK18_base_F : RHARD_MK18_base {
		class WeaponSlotsInfo;
	};
	
	class RHARD_M4_base_F : rhs_weap_m4a1_blockII {
		descriptionShort = M4A1;
		
		};
		
		class Library {
			libTextDesc = "M4A1 Block 2 Carbine";
		};
		
		class ItemInfo {
			priority = 1;
			RMBhint = "M4A1 Block 2";
			onHoverText = "M4A1 Block 2";
		};
		
	};
	
	class RHARD_MK18_F : RHARD_MK18_base_F {
		scope = public;
		model = "\rhard_mk18\RHARD_MK18.p3d";
		displayName = "MK18 MOD 1";
		picture = "\RHARD_MK18\data\ui\gear_MK18_x_ca.paa";
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"\rhard_mk18\tx\base1_co.paa", "\rhard_mk18\tx\base2_co.paa"};
		author = RHARD;
	};
	
	class RHARD_MK18D_F : RHARD_MK18_base_F {
		scope = public;
		model = "\rhard_mk18\RHARD_MK18.p3d";
		displayName = "MK18 MOD 1 Des";
		picture = "\RHARD_MK18\data\ui\gear_MK18D_x_ca.paa";
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"\rhard_mk18\tx\base1d_co.paa", "\rhard_mk18\tx\base2d_co.paa"};
		author = RHARD;
	};
	
	class RHARD_MK18P_F : RHARD_MK18_base_F {
		scope = public;
		model = "\rhard_mk18\RHARD_MK18P.p3d";
		displayName = "MK18 MOD 1 Pmag";
		picture = "\RHARD_MK18\data\ui\gear_MK18P_x_ca.paa";
		hiddenSelections[] = {"camo1", "camo2", "pmag", "mstock"};
		hiddenSelectionsTextures[] = {"\rhard_mk18\tx\base1_co.paa", "\rhard_mk18\tx\base2_co.paa", "\rhard_mk18\tx\pmagb_co.paa", "\rhard_mk18\tx\mstock_co.paa"};
		author = RHARD;
	};
	
	class RHARD_MK18PD_F : RHARD_MK18_base_F {
		scope = public;
		model = "\rhard_mk18\RHARD_MK18P.p3d";
		displayName = "MK18 MOD 1 Pmag Des";
		picture = "\RHARD_MK18\data\ui\gear_MK18DP_x_ca.paa";
		hiddenSelections[] = {"camo1", "camo2", "pmag", "mstock"};
		hiddenSelectionsTextures[] = {"\rhard_mk18\tx\base1d_co.paa", "\rhard_mk18\tx\base2d_co.paa", "\rhard_mk18\tx\pmag_co.paa", "\rhard_mk18\tx\mstock_TANCAM_co.paa"};
		author = RHARD;
	};
	
	class RHARD_MK18E_F : RHARD_MK18_base_F {
		scope = public;
		model = "\rhard_mk18\RHARD_MK18_B.p3d";
		displayName = "MK18 MOD 1 (KAC)";
		handAnim[] = {"OFP2_ManSkeleton", "\RHARD_MK18\anim\MK18_rail.rtm"};
		picture = "\RHARD_MK18\data\ui\gear_MK18_B_x_ca.paa";
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"\rhard_mk18\tx\base1_co.paa", "\rhard_mk18\tx\base2_co.paa"};
		author = RHARD;
	};
	
	class RHARD_MK18ED_F : RHARD_MK18_base_F {
		scope = public;
		model = "\rhard_mk18\RHARD_MK18_B.p3d";
		displayName = "MK18 MOD 1 Des (KAC)";
		handAnim[] = {"OFP2_ManSkeleton", "\RHARD_MK18\anim\MK18_rail.rtm"};
		picture = "\RHARD_MK18\data\ui\gear_MK18D_B_x_ca.paa";
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"\rhard_mk18\tx\base1d_co.paa", "\rhard_mk18\tx\base2d_co.paa"};
		author = RHARD;
	};
	
	class RHARD_MK18AFG_F : RHARD_MK18_base_F {
		scope = public;
		model = "\rhard_mk18\RHARD_MK18AFG.p3d";
		displayName = "MK18 MOD 1 AFG";
		handAnim[] = {"OFP2_ManSkeleton", "\RHARD_MK18\anim\mk18_afg.rtm"};
		picture = "\RHARD_MK18\data\ui\gear_MK18AFG_x_ca.paa";
		hiddenSelections[] = {"camo1", "camo2", "pmag", "mstock"};
		hiddenSelectionsTextures[] = {"\rhard_mk18\tx\base1_co.paa", "\rhard_mk18\tx\base2_co.paa", "\rhard_mk18\tx\pmagb_co.paa", "\rhard_mk18\tx\mstock_TANCAM_co.paa"};
		
		class WeaponSlotsInfo : WeaponSlotsInfo {
			class UnderBarrelSlot {};
		};
		author = RHARD;
	};
	
	class RHARD_MK18AFGD_F : RHARD_MK18_base_F {
		scope = public;
		model = "\rhard_mk18\RHARD_MK18AFG.p3d";
		displayName = "MK18 MOD 1 AFG Des";
		handAnim[] = {"OFP2_ManSkeleton", "\RHARD_MK18\anim\mk18_afg.rtm"};
		picture = "\RHARD_MK18\data\ui\gear_MK18DAFG_x_ca.paa";
		hiddenSelections[] = {"camo1", "camo2", "pmag", "mstock"};
		hiddenSelectionsTextures[] = {"\rhard_mk18\tx\base1d_co.paa", "\rhard_mk18\tx\base2d_co.paa", "\rhard_mk18\tx\pmag_co.paa", "\rhard_mk18\tx\mstock_TANCAM_co.paa"};
		
		class WeaponSlotsInfo : WeaponSlotsInfo {
			class UnderBarrelSlot {};
		};
		author = RHARD;
	};
	
	class RHARD_MK18AFG_B_F : RHARD_MK18_base_F {
		scope = public;
		model = "\rhard_mk18\RHARD_MK18AFG_B.p3d";
		displayName = "MK18 MOD 1 AFG (KAC)";
		handAnim[] = {"OFP2_ManSkeleton", "\RHARD_MK18\anim\mk18_afg_2.rtm"};
		picture = "\RHARD_MK18\data\ui\gear_MK18AFG_B_x_ca.paa";
		hiddenSelections[] = {"camo1", "camo2", "pmag"};
		hiddenSelectionsTextures[] = {"\rhard_mk18\tx\base1_co.paa", "\rhard_mk18\tx\base2_co.paa", "\rhard_mk18\tx\pmagb_co.paa"};
		author = RHARD;
	};
	
	class RHARD_MK18AFGD_B_F : RHARD_MK18_base_F {
		scope = public;
		model = "\rhard_mk18\RHARD_MK18AFG_B.p3d";
		displayName = "MK18 MOD 1 AFG Des (KAC)";
		handAnim[] = {"OFP2_ManSkeleton", "\RHARD_MK18\anim\mk18_afg_2.rtm"};
		picture = "\RHARD_MK18\data\ui\gear_MK18DAFG_B_x_ca.paa";
		hiddenSelections[] = {"camo1", "camo2", "pmag"};
		hiddenSelectionsTextures[] = {"\rhard_mk18\tx\base1d_co.paa", "\rhard_mk18\tx\base2d_co.paa", "\rhard_mk18\tx\pmagb_co.paa"};
		author = RHARD;
	};
	
	class RHARD_M4DDR_F : RHARD_M4_base_F {
		scope = public;
		model = "\rhard_mk18\RHARD_M4DDR_B.p3d";
		displayName = "M4 Block 2 (KAC)";
		handAnim[] = {"OFP2_ManSkeleton", "\RHARD_MK18\anim\MK18_rail.rtm"};
		picture = "\RHARD_MK18\data\ui\gear_M4_B_x_ca.paa";
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"\rhard_mk18\tx\m4a1_co.paa", "\rhard_mk18\tx\dd2_m4_co.paa"};
		author = RHARD;
	};
	
	class RHARD_M4DDRD_F : RHARD_M4_base_F {
		scope = public;
		model = "\rhard_mk18\RHARD_M4DDR_B.p3d";
		displayName = "M4 Block 2 Des (KAC)";
		picture = "\RHARD_MK18\data\ui\gear_M4D_B_x_ca.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\RHARD_MK18\anim\MK18_rail.rtm"};
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"\rhard_mk18\tx\m4a1d_co.paa", "\rhard_mk18\tx\dd2_m4d_co.paa"};
		author = RHARD;
	};
	
	class RHARD_M4DDR_B_F : RHARD_M4_base_F {
		scope = public;
		model = "\rhard_mk18\RHARD_M4DDR.p3d";
		displayName = "M4 Block 2 FG";
		handAnim[] = {"OFP2_ManSkeleton", "\RHARD_MK18\anim\M4_Fg.rtm"};
		picture = "\RHARD_MK18\data\ui\gear_M4_x_ca.paa";
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"\rhard_mk18\tx\m4a1_co.paa", "\rhard_mk18\tx\dd2_m4_co.paa"};
		author = RHARD;
	};
	
	class RHARD_M4DDRD_B_F : RHARD_M4_base_F {
		scope = public;
		model = "\rhard_mk18\RHARD_M4DDR.p3d";
		displayName = "M4 Block 2 FG Des";
		handAnim[] = {"OFP2_ManSkeleton", "\RHARD_MK18\anim\M4_Fg.rtm"};
		picture = "\RHARD_MK18\data\ui\gear_M4D_x_ca.paa";
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"\rhard_mk18\tx\m4a1d_co.paa", "\rhard_mk18\tx\dd2_m4d_co.paa"};
		author = RHARD;
	};
	
	class RHARD_M4DDRP_F : RHARD_M4_base_F {
		scope = public;
		model = "\rhard_mk18\RHARD_M4DDRP.p3d";
		displayName = "M4 Block 2 AFG";
		handAnim[] = {"OFP2_ManSkeleton", "\RHARD_MK18\anim\mk18_afg.rtm"};
		picture = "\RHARD_MK18\data\ui\gear_M4P_x_ca.paa";
		hiddenSelections[] = {"camo1", "camo2", "pmag", "mstock"};
		hiddenSelectionsTextures[] = {"\rhard_mk18\tx\m4a1_co.paa", "\rhard_mk18\tx\dd2_m4_co.paa", "\rhard_mk18\tx\pmagb_co.paa", "\rhard_mk18\tx\mstock_co.paa"};
		author = RHARD;
	};
	
	class RHARD_M4DDRPD_F : RHARD_M4_base_F {
		scope = public;
		model = "\rhard_mk18\RHARD_M4DDRP.p3d";
		displayName = "M4 Block 2 AFG Des";
		handAnim[] = {"OFP2_ManSkeleton", "\RHARD_MK18\anim\mk18_afg.rtm"};
		picture = "\RHARD_MK18\data\ui\gear_M4DP_x_ca.paa";
		hiddenSelections[] = {"camo1", "camo2", "pmag", "mstock"};
		hiddenSelectionsTextures[] = {"\rhard_mk18\tx\m4a1d_co.paa", "\rhard_mk18\tx\dd2_m4d_co.paa", "\rhard_mk18\tx\pmag_co.paa", "\rhard_mk18\tx\mstock_TANCAM_co.paa"};
		author = RHARD;
	};
	
	
};

class cfgMods {
	author = 76561197992542134;
	timepacked = 1434483434;
};
